export const translations = {
  en: {
    title: "Create Next App",
    description: "Generated by create next app",
    nav: {
      home: "Home",
      about: "About Us",
      gallery: "Gallery",
      contact: "Contact"
    },
    buttons: {
      languageToggle: "Switch to Deutsch",
      reservation: "Book Now"
    },
    business: {
      description: "Restaurant & Lieferservice",
      address: "Street Address 123, City",
      tel: "Tel: +49 123 456789",
      service: {
        services: "In House | Pickup | Delivery"
      },
      buttons: {
        menu: "Menu",
        order: "Order",
        more: "See More"
      }
    },
    profile: {
      title: "5 BRANDS, 7 OUTLETS, 20 YEARS OF EXPERIENCE",
      description: "Welcome to Restaurant Die Wunderlampe. Immerse yourself in a fairy tale from A Thousand and One Nights! Oriental flair, exotic aromas and a lovingly designed ambience await you inside and out. Whether cozy indoors or relaxed in the beer garden. Enjoy our diverse specialties for every taste: hearty or light, exotic or classic, vegetarian-vegan or with meat.",
      button: "See More"
    }
  },
  de: {
    title: "Next App Erstellen",
    description: "Erstellt mit create next app",
    nav: {
      home: "Startseite",
      about: "Über uns",
      gallery: "Galerie",
      contact: "Kontakt"
    },
    buttons: {
      languageToggle: "Switch to English",
      reservation: "Jetzt Buchen"
    },
    business: {
      description: "Restaurant & Lieferservice",
      address: "Straße 123, Stadt",
      tel: "Tel: +49 123 456789",
      service: {
        services: "Im Haus | Abholung | Lieferung"
      },
      buttons: {
        menu: "Speisekarte",
        order: "Bestellung",
        more: "Siehe mehr"
      }
    },
    profile: {
      title: "5 BRANDS, 7 OUTLETS, 20 YEARS OF EXPERIENCE",
      description: "Willkommen im Restaurant Die Wunderlampe. Tauchen Sie ein in ein Märchen aus Tausendundeiner Nacht! Orientalisches Flair, exotische Düfte und ein liebevoll gestaltetes Ambiente erwarten Sie drinnen wie draußen. Ob gemütlich im Innenbereich oder entspannt im Biergarten. Genießen Sie unsere vielfältigen Spezialitäten für jeden Geschmack: herzhaft oder leicht, exotisch oder klassisch, vegetarisch-vegan oder mit Fleisch.",
      button: "Siehe Mehr"
    }
  }
};
