export const translations = {
  en: {
    title: "Create Next App",
    description: "Generated by create next app",
    nav: {
      home: "Home",
      about: "About",
      contact: "Contact"
    },
    buttons: {
      languageToggle: "Switch to Deutsch"
    }
  },
  de: {
    title: "Next App Erstellen",
    description: "Erstellt mit create next app",
    nav: {
      home: "Startseite",
      about: "Über uns",
      contact: "Kontakt"
    },
    buttons: {
      languageToggle: "Switch to English"
    }
  }
};
