
import { Aladin, JetBrains_Mono, Poppins } from "next/font/google";
import { LanguageProvider } from "@/context/LanguageContext";
import { Header } from "@/components/Header";
import "./globals.css";

const aladin = Aladin({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fonts = {
  aladin,
  jetbrainsMono,
  poppins
};

export default function RootLayout({ children }) {
  return (
    <html lang="de">
      <body
        className={`${poppins.className} antialiased bg-white font-poppins`}
      >
        <LanguageProvider>
          <Header />
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
